Minor gettext compatibility fix
adams85/po pull request #20
Opened 2022-06-27 15:23 UTC by samhocevar

When a translator comment is empty, gettext writes a line containing `# `, whereas
Karambolo.PO would output `#  `. The behaviour is now more consistent.

2022-06-27 15:25 UTC, samhocevar commented
Sorry, it looks like markdown rendering made my explanation not entirely clear.
 - gettext outputs `#` `<space>`
 - Karambolo.PO outputs `#` `<space>` `<space>`

2022-06-28 09:15 UTC, adams85 commented
Nice finding! Thank you for reporting it.

Your fix is alright apart from that minor issue I pointed out. Please set this straight and add a test case to `POGeneratorTest`, then I'll merge it.

2022-06-28 13:41 UTC, samhocevar commented
I’m sorry, where can I find about this issue? (note that I force-pushed my branch yesterday so if there was a comment on the initial code GitHub may have lost it)

2022-06-28 16:30 UTC, adams85 commented
I've started a review and commented your code, you should see it above. No force pushes have happened since then.

2022-06-28 20:19 UTC, samhocevar commented
Is the review still a draft maybe? Because the GitHub interface says “No reviews” for me, and the “Files changed” tab only shows the diff, with no annotations.

2022-06-28 20:41 UTC, adams85 requested changes

2022-06-28 20:42 UTC, adams85 commented
Sorry, it looks like I forgot to finish the review. Now it should be visible to you.

2022-09-17 21:36 UTC, merged